version: "3.7"
services:
  test_task_backend:
    container_name: test_task_backend
    build:
      context: mainapp/.
      dockerfile: Dockerfile
    image: mainapp
    restart: unless-stopped
    ports:
        - "5000:5000"
    depends_on:
        - test_rabbitmq
        - test_task_postgres
    links:
        - test_task_postgres:test_task_postgres
        - test_rabbitmq:test_rabbitmq
    networks:
        - tesk_task_network
  test_task_worker:
    container_name: test_task_worker
    build:
      context: notification-worker/.
      dockerfile: Dockerfile
    image: test_task_worker
    restart: unless-stopped
    depends_on:
      - test_rabbitmq
    links:
      - test_rabbitmq:test_rabbitmq
    networks:
      - tesk_task_network
  test_task_postgres:
    container_name: test_task_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - tesk_task_network


  test_task_pgadmin:
    links:
      - test_task_postgres:test_task_postgres
    container_name: test_task_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - tesk_task_network

  test_rabbitmq:
    image: rabbitmq:3-management
    container_name: test_rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env
    networks:
      - tesk_task_network


networks:
  tesk_task_network:
