version: "3.7"
services:
  test_task_postgres:
    container_name: test_task_postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - test_task_postgres
  test_task_pgadmin:
    links:
      - test_task_postgres:test_task_postgres
    container_name: test_task_pgadmin
    image: dpage/pgadmin4
    ports:
      - "8080:80"
    volumes:
      - /data/pgadmin:/root/.pgadmin
    env_file:
      - docker.env
    networks:
      - test_task_postgres
  test_rabbitmq:
    image: rabbitmq:3-management
    container_name: test_rabbitmq
    hostname: rabbitmq
    volumes:
      - /var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - ./rabbitmq.env

networks:
  test_task_postgres:
    driver: bridge
